title: Neko Map
description: Track and Care for Cats on the UH Manoa Campus 
google_analytics:
show_downloads: false
theme: jekyll-theme-slate
github:
  is_project_page: false
gems:
  - jekyll-mentions
